version: '3'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    links:
      - db:mysql

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: meu_banco_de_dados
      MYSQL_USER: meu_usuario
      MYSQL_PASSWORD: meu_password
    ports:
      - "3307:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: meu_usuario
      PMA_PASSWORD: meu_password
    ports:
      - "8081:80"
    links:
      - db
