name: Docker Swarm Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

    - name: Build and push Docker image
      run: |
        IMAGE_ID=$(docker build -t $DOCKER_USERNAME/docker-swarm-felipe:$GITHUB_SHA . | awk '/Successfully built/ { print $3 }')
        docker push $DOCKER_USERNAME/docker-swarm-felipe:$GITHUB_SHA
        echo "$EC2_SSH_KEY" > ssh_key.pem
        chmod 600 ssh_key.pem
        ssh -i ssh_key.pem ec2-user@ec2-100-26-137-168.compute-1.amazonaws.com "docker service update --image $DOCKER_USERNAME/docker-swarm-felipe:$GITHUB_SHA service-felipe_web"
